[Interface]
PrivateKey = +B2YJpng0AnA1sc7nEQuxb6ncBqdqM6E3eZOxt0PQ2w=
Address = 87.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = AplIbKncuaxK9+gVr419UeFtzW26ujIbuuqsyi1htTo=
Endpoint = 140.131.114.152:51820
AllowedIPs = 87.0.0.0/24
PersistentKeepalive = 25
