# Generated by Django 5.2.14 on 2026-05-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('normalized_url', models.URLField(db_index=True, max_length=2048)),
                ('origin', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', '等待中'), ('crawling', '爬取中'), ('scanning', '掃描中'), ('agent_testing', 'Agent 測試中'), ('completed', '已完成'), ('failed', '失敗')], db_index=True, default='queued', max_length=32)),
                ('scan_mode', models.CharField(choices=[('passive', '被動偵測'), ('active', '主動測試')], db_index=True, default='passive', max_length=16)),
                ('max_depth', models.PositiveSmallIntegerField(default=3)),
                ('max_pages', models.PositiveIntegerField(default=50)),
                ('respect_robots', models.BooleanField(default=True)),
                ('active_testing_authorized', models.BooleanField(default=False)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('top_actions', models.JSONField(blank=True, default=list)),
                ('crawl_checkpoint', models.JSONField(blank=True, default=dict)),
                ('warning_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(db_index=True, max_length=2048)),
                ('origin', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('html', models.TextField(blank=True)),
                ('rendered_dom', models.TextField(blank=True)),
                ('html_only_text', models.TextField(blank=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=1024)),
                ('load_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('depth', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fetch_mode', models.CharField(choices=[('live', '即時爬取'), ('cache_replay', '快取重放')], default='live', max_length=32)),
                ('blocked_reason', models.CharField(blank=True, max_length=255)),
                ('outgoing_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scans.scanjob')),
            ],
            options={
                'ordering': ['depth', 'url'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', '嚴重'), ('high', '高'), ('medium', '中'), ('low', '低'), ('info', '資訊')], db_index=True, max_length=16)),
                ('category', models.CharField(choices=[('seo', 'SEO'), ('aeo', 'AEO'), ('geo', 'GEO'), ('security', '資安'), ('ux', 'UX')], db_index=True, max_length=16)),
                ('priority_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('impact_area', models.CharField(blank=True, max_length=128)),
                ('confidence', models.FloatField(default=1.0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remediation', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('selector', models.CharField(blank=True, max_length=512)),
                ('ai_handoff_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.page')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-priority_score', 'severity', 'category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('authorized_domain', models.CharField(db_index=True, max_length=255)),
                ('statement', models.TextField()),
                ('active_testing_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_consents', to=settings.AUTH_USER_MODEL)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_consent', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('queued', '等待中'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗')], db_index=True, default='queued', max_length=32)),
                ('max_steps', models.PositiveSmallIntegerField(default=20)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('observation', models.TextField(blank=True)),
                ('thought_summary', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('tool_arguments', models.JSONField(blank=True, default=dict)),
                ('tool_result', models.JSONField(blank=True, default=dict)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scans.agentsession')),
            ],
            options={
                'ordering': ['step_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'step_number'), name='unique_agent_step_per_session')],
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['user', 'status'], name='scans_scanj_user_id_8e2e98_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['origin', 'created_at'], name='scans_scanj_origin_d3e163_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['scan_job', 'depth'], name='scans_page_scan_jo_3694e1_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['origin', 'status_code'], name='scans_page_origin_ba91bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('scan_job', 'url'), name='unique_page_per_scan'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan_job', 'category', 'severity'], name='scans_findi_scan_jo_e5808b_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['page', 'category'], name='scans_findi_page_id_0a116c_idx'),
        ),
    ]
