# Generated by Django 5.2.14 on 2026-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_page_element_boxes_page_headers_userscanquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
