# Generated by Django 5.2.14 on 2026-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scanjob_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('queued', '等待中'), ('crawling', '爬取中'), ('scanning', '掃描中'), ('agent_testing', 'Agent 測試中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已終止')], db_index=True, default='queued', max_length=32),
        ),
    ]
