# Generated by Django 5.2.14 on 2026-05-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_scanjob_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScanQuota',
        ),
    ]
