# Generated by Django 5.2.14 on 2026-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_delete_userscanquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='scan_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
