# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0006_add_scan_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="ai_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_remediation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="evidence_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="finding",
            name="evidence_source",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="finding",
            name="evidence_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="finding",
            name="llm_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="llm_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="finding",
            name="rule_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
