# Generated by Codex on 2026-06-04

import hashlib
import re

from django.db import migrations


def _normalize_rule_token(value: str) -> str:
    token = re.sub(r"[^0-9A-Za-z]+", "_", value or "").strip("_").upper()
    return token[:80] or "GENERAL"


def _default_rule_id(category: str, title: str) -> str:
    digest = hashlib.sha1((title or "").encode("utf-8")).hexdigest()[:10].upper()
    return f"{_normalize_rule_token(category)}_{_normalize_rule_token(title)}_{digest}"


def backfill_evidence_metadata(apps, schema_editor):
    Finding = apps.get_model("scans", "Finding")
    qs = Finding.objects.filter(rule_id="")
    for finding in qs.iterator(chunk_size=500):
        evidence_type = finding.evidence_type or "text"
        evidence_source = finding.evidence_source or "legacy_rule_engine"
        evidence_json = finding.evidence_json or {
            "type": evidence_type,
            "source": evidence_source,
            "excerpt": (finding.evidence or "")[:1000],
            "backfilled": True,
        }
        Finding.objects.filter(pk=finding.pk).update(
            rule_id=_default_rule_id(finding.category or "finding", finding.title or ""),
            evidence_type=evidence_type,
            evidence_json=evidence_json,
            evidence_source=evidence_source,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0007_finding_evidence_first_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_evidence_metadata, migrations.RunPython.noop),
    ]
