# Generated by Django 5.2.14 on 2026-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_backfill_finding_evidence_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cwe_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='finding',
            name='owasp_category',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
