# Generated by Django 5.2.14 on 2026-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_finding_cwe_id_finding_owasp_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': [models.OrderBy(models.F('priority_score'), descending=True, nulls_last=True), models.Case(models.When(severity='critical', then=models.Value(0)), models.When(severity='high', then=models.Value(1)), models.When(severity='medium', then=models.Value(2)), models.When(severity='low', then=models.Value(3)), models.When(severity='info', then=models.Value(4)), default=models.Value(5), output_field=models.IntegerField()), 'category', '-created_at']},
        ),
    ]
