# Generated by Django 5.2.14 on 2026-08-31 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_alter_finding_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('content_sha256', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_verification', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
