# Generated by Django 5.2.14 on 2026-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_reportverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportverification',
            name='previous_sha256',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportverification',
            name='renderer_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
