# Generated by Django 5.2.14 on 2026-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_reportverification_previous_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
