# Generated by Django 5.2.14 on 2026-09-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_page_layout_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', '尚未產生'), ('generating', '產生中'), ('ready', '已完成'), ('failed', '失敗')], db_index=True, default='idle', max_length=16)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix_output', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
