# Generated by Django 5.2.14 on 2026-09-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_fixoutput'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '待驗證'), ('verified', '已驗證'), ('rejected', '已否決'), ('expired', '已過期')], db_index=True, default='pending', max_length=16)),
                ('method', models.CharField(blank=True, choices=[('dns_txt', 'DNS TXT 記錄'), ('meta_tag', 'HTML meta 標籤'), ('html_file', '驗證檔案')], default='', max_length=16)),
                ('token', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('admin_override', models.BooleanField(default=False)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='unique_verified_domain_per_user')],
            },
        ),
    ]
