# Generated by Django 5.2.14 on 2026-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_verifieddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='test_auth_email_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='test_auth_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='max_pages',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
