# Generated by Django 5.2.14 on 2026-09-25 17:07

import apps.scans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0016_scanjob_test_auth_email_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='categories',
            field=models.JSONField(default=apps.scans.models.default_categories),
        ),
    ]
