# Generated by Django 5.2.14 on 2026-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0017_scanjob_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="aeo_report",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
