# Generated by Django 5.2.14 on 2026-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0018_scanjob_aeo_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieddomain',
            name='method',
            field=models.CharField(blank=True, choices=[('dns_txt', 'DNS TXT 記錄'), ('meta_tag', 'HTML meta 標籤'), ('html_file', '驗證檔案'), ('google_search_console', 'Google Search Console')], default='', max_length=32),
        ),
    ]
