# Generated by Django 5.2.14 on 2026-09-29 16:12

from urllib.parse import urlparse

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.scans.models


def drop_orphaned_site_project_schema(apps, schema_editor):
    """清掉先前被回退的網站專案版本留下的表與欄位，讓本 migration 能從乾淨狀態建立。

    這個 migration 還沒套用時，`scans_siteproject` 與 `scans_scanjob.project_id` 不應該存在；
    若存在，只可能是同一功能較早的版本曾在這個資料庫跑過、之後程式與 migration 紀錄被回退
    但資料表沒有一起刪除（2026-10-02 實際發生：Docker 的 migrate 報 relation already exists）。
    專案資料可由下方 backfill 依既有掃描重建，掃描、finding 與點數紀錄都不受影響。
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = set(connection.introspection.table_names(cursor))
        scan_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "scans_scanjob")
        }
    if "project_id" in scan_columns:
        if connection.vendor == "sqlite":
            # SQLite 的 DROP COLUMN 會被欄位上的索引擋下，先刪索引
            with connection.cursor() as cursor:
                constraints = connection.introspection.get_constraints(cursor, "scans_scanjob")
            for name, info in constraints.items():
                if info["index"] and info["columns"] == ["project_id"]:
                    schema_editor.execute(f"DROP INDEX {schema_editor.quote_name(name)}")
            schema_editor.execute("ALTER TABLE scans_scanjob DROP COLUMN project_id")
        else:
            # 用同欄名的一般整數欄位移除，不需解析關聯目標；
            # PostgreSQL 以 DROP COLUMN ... CASCADE 連同外鍵與索引一起刪
            stale_column = models.BigIntegerField(null=True)
            stale_column.set_attributes_from_name("project_id")
            schema_editor.remove_field(apps.get_model("scans", "ScanJob"), stale_column)
        print("\n  已移除先前版本殘留的 scans_scanjob.project_id 欄位", end="")
    if "scans_siteproject" in tables:
        table = schema_editor.quote_name("scans_siteproject")
        schema_editor.execute(schema_editor.sql_delete_table % {"table": table})
        print("\n  已移除先前版本殘留的 scans_siteproject 表（專案會依既有掃描重新回填）", end="")


def backfill_site_projects(apps, schema_editor):
    """既有掃描依 (使用者, origin) 建立網站專案並歸入；起始網址取該 origin 最新一次掃描的網址。"""
    ScanJob = apps.get_model("scans", "ScanJob")
    SiteProject = apps.get_model("scans", "SiteProject")
    pairs = (
        ScanJob.objects.filter(project__isnull=True)
        .exclude(origin="")
        .values_list("user_id", "origin")
        .distinct()
    )
    for user_id, origin in list(pairs):
        latest = (
            ScanJob.objects.filter(user_id=user_id, origin=origin).order_by("-created_at").first()
        )
        project, _ = SiteProject.objects.get_or_create(
            user_id=user_id,
            origin=origin,
            defaults={
                "name": ((urlparse(origin).hostname or origin).lower())[:80],
                "start_url": (latest.normalized_url if latest else "") or f"{origin}/",
            },
        )
        ScanJob.objects.filter(user_id=user_id, origin=origin, project__isnull=True).update(
            project=project
        )


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0018_scanjob_aeo_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_orphaned_site_project_schema, migrations.RunPython.noop),
        migrations.CreateModel(
            name="SiteProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("origin", models.CharField(db_index=True, max_length=255)),
                ("start_url", models.URLField(max_length=2048)),
                (
                    "default_scope",
                    models.CharField(
                        choices=[("site", "整個網站"), ("single", "單一頁面")],
                        default="site",
                        max_length=8,
                    ),
                ),
                (
                    "default_categories",
                    models.JSONField(default=apps.scans.models.default_categories),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scanjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="scans.siteproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="siteproject",
            constraint=models.UniqueConstraint(
                fields=("user", "origin"), name="uniq_site_project_user_origin"
            ),
        ),
        migrations.RunPython(backfill_site_projects, migrations.RunPython.noop),
    ]
