# Generated by Django 5.2.14 on 2026-09-29 16:12

from urllib.parse import urlparse

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.scans.models


def backfill_site_projects(apps, schema_editor):
    """既有掃描依 (使用者, origin) 建立網站專案並歸入；起始網址取該 origin 最新一次掃描的網址。"""
    ScanJob = apps.get_model("scans", "ScanJob")
    SiteProject = apps.get_model("scans", "SiteProject")
    pairs = (
        ScanJob.objects.filter(project__isnull=True)
        .exclude(origin="")
        .values_list("user_id", "origin")
        .distinct()
    )
    for user_id, origin in list(pairs):
        latest = (
            ScanJob.objects.filter(user_id=user_id, origin=origin).order_by("-created_at").first()
        )
        project, _ = SiteProject.objects.get_or_create(
            user_id=user_id,
            origin=origin,
            defaults={
                "name": ((urlparse(origin).hostname or origin).lower())[:80],
                "start_url": (latest.normalized_url if latest else "") or f"{origin}/",
            },
        )
        ScanJob.objects.filter(user_id=user_id, origin=origin, project__isnull=True).update(
            project=project
        )


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0018_scanjob_aeo_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("origin", models.CharField(db_index=True, max_length=255)),
                ("start_url", models.URLField(max_length=2048)),
                (
                    "default_scope",
                    models.CharField(
                        choices=[("site", "整個網站"), ("single", "單一頁面")],
                        default="site",
                        max_length=8,
                    ),
                ),
                (
                    "default_categories",
                    models.JSONField(default=apps.scans.models.default_categories),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scanjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="scans.siteproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="siteproject",
            constraint=models.UniqueConstraint(
                fields=("user", "origin"), name="uniq_site_project_user_origin"
            ),
        ),
        migrations.RunPython(backfill_site_projects, migrations.RunPython.noop),
    ]
