# Generated by Django 5.2.14 on 2026-10-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0019_site_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteproject",
            name="favicon",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="siteproject",
            name="favicon_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
