# Generated by Django 5.2.14 on 2026-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0020_site_project_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteproject",
            name="default_scan_mode",
            field=models.CharField(default="passive", max_length=16),
        ),
        migrations.AddField(
            model_name="siteproject",
            name="description",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="siteproject",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
