# Generated by Django 5.2.14 on 2026-10-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0021_site_project_demo_and_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="seo_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="siteproject",
            name="target_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="SearchConsoleConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_token_encrypted", models.TextField()),
                (
                    "property_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_console",
                        to="scans.siteproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_consoles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
