# Generated by Django 5.2.14 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0022_seo_analysis_and_search_console"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifieddomain",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dns_txt", "DNS TXT 記錄"),
                    ("meta_tag", "HTML meta 標籤"),
                    ("html_file", "驗證檔案"),
                    ("search_console", "Google Search Console"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
