# Generated by Django 5.2.14 on 2026-10-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0023_verifieddomain_search_console"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchconsoleconnection",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_console",
                to="scans.siteproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchconsoleconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("user",),
                name="uniq_account_level_search_console",
            ),
        ),
    ]
