# Generated by Django 5.2.14 on 2026-10-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0023_merge_gsc_and_projects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifieddomain",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dns_txt", "DNS TXT 記錄"),
                    ("meta_tag", "HTML meta 標籤"),
                    ("html_file", "驗證檔案"),
                    ("google_search_console", "Google Search Console"),
                    ("search_console", "Google Search Console"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="searchconsoleconnection",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_console",
                to="scans.siteproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchconsoleconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("user",),
                name="uniq_account_level_search_console",
            ),
        ),
    ]
