# Generated by Django 5.2.14 on 2026-10-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # 只依賴 0022：正式資料庫套用過舊鏈（0019_alter_verifieddomain_method →
    # 0023_merge_gsc_and_projects → 本檔），開發環境可能套用過已移除的
    # 0023_verifieddomain_search_console；兩邊都已套用 0022，依賴它才不會出現
    # InconsistentMigrationHistory（2026-10-04 K8s migrate 事故）。
    dependencies = [
        ("scans", "0022_seo_analysis_and_search_console"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchconsoleconnection",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_console",
                to="scans.siteproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchconsoleconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("user",),
                name="uniq_account_level_search_console",
            ),
        ),
    ]
