# Generated by Django 5.2.14 on 2026-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0025_verifieddomain_method_search_console"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="site_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
