# Generated by Django 5.2.14 on 2026-09-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0012_reportverification_previous_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRebuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('snapshotting', '複刻中'), ('optimizing', '優化中'), ('succeeded', '完成'), ('failed', '失敗')], db_index=True, default='pending', max_length=16)),
                ('snapshot_path', models.CharField(blank=True, max_length=512)),
                ('optimized_path', models.CharField(blank=True, max_length=512)),
                ('opencode_session_id', models.CharField(blank=True, max_length=128)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuilds', to='scans.page')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuilds', to='scans.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scan_job', 'status'], name='rebuild_sit_scan_jo_2bfd89_idx')],
            },
        ),
    ]
