# Generated by Django 5.2.14 on 2026-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebuild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterebuild',
            name='coins_charged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
