# Generated by Django 5.2.14 on 2026-09-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebuild', '0002_siterebuild_coins_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterebuild',
            name='trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
