# Generated by Django 5.2.14 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebuild', '0003_siterebuild_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterebuild',
            name='edit_report',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
