# Generated by Django 5.2.14 on 2026-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebuild', '0004_siterebuild_edit_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterebuild',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='siterebuild',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siterebuild',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('snapshotting', '複刻中'), ('optimizing', '優化中'), ('asking', '回答中'), ('succeeded', '完成'), ('failed', '失敗')], db_index=True, default='pending', max_length=16),
        ),
    ]
