# Generated by Django 5.2.14 on 2026-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rebuild", "0005_siterebuild_conversation_siterebuild_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siterebuild",
            name="share_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siterebuild",
            name="share_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
