# Generated by Django 5.2.14 on 2026-10-06 14:03

from django.db import migrations, models


def keep_existing_links(apps, schema_editor):
    """已分享（有 token）的舊連結維持「知道連結的任何人」，原本的期限照舊。"""
    SiteRebuild = apps.get_model("rebuild", "SiteRebuild")
    SiteRebuild.objects.exclude(share_token="").update(share_access="link")


class Migration(migrations.Migration):

    dependencies = [
        ("rebuild", "0006_siterebuild_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="siterebuild",
            name="outcome",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="siterebuild",
            name="share_access",
            field=models.CharField(
                choices=[
                    ("private", "僅限本人"),
                    ("link", "知道連結的任何人"),
                    ("login", "知道連結且已登入 Argus 的人"),
                ],
                default="private",
                max_length=16,
            ),
        ),
        migrations.RunPython(keep_existing_links, migrations.RunPython.noop),
    ]
