# Generated by Django 5.2.14 on 2026-05-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('platform', models.CharField(choices=[('pwa', 'PWA（瀏覽器安裝）'), ('android', 'Android'), ('ios', 'iOS'), ('desktop', '桌面')], default='pwa', max_length=16)),
                ('release_notes', models.TextField(blank=True)),
                ('download_url', models.URLField(blank=True, help_text='外部下載連結；PWA 留空表示「站內安裝」')),
                ('icon_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_latest', models.BooleanField(default=False, help_text='標記為最新版（前台顯示徽章）')),
                ('released_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, help_text='emoji 或圖示字串', max_length=16)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(help_text='例如：前端工程師、UX 設計師', max_length=64)),
                ('avatar_emoji', models.CharField(blank=True, help_text='一個 emoji 當頭像，例如 🧑\u200d💻、🎨', max_length=8)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text="技能 chip 列表，例如 ['React', 'Django', 'Figma']")),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
