# Generated by Django 5.2.14 on 2026-05-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contributions',
            field=models.JSONField(blank=True, default=list, help_text="分工項目列表，每項 {title, desc}，例如 [{title:'Playwright 爬蟲', desc:'BFS + RPS'}]"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skill_levels',
            field=models.JSONField(blank=True, default=list, help_text="技能熟練度列表，每項 {name, level 0-100}，例如 [{name:'React', level: 90}]"),
        ),
    ]
