# Generated by Django 5.2.14 on 2026-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_seed_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='大頭照圖片 URL；留空時使用 avatar_emoji'),
        ),
    ]
