# Generated by Django 5.2.14 on 2026-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_avatar_url_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='學號（公開團隊頁顯示），例：11246034', max_length=20),
        ),
    ]
