# Generated by Django 5.2.14 on 2026-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_scrub_team_school_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("company", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("agency", "網站開發與數位代理"),
                            ("operations", "維運與技術服務"),
                            ("platform", "平台與技術合作"),
                            ("other", "其他"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "site_count",
                    models.CharField(
                        blank=True,
                        help_text="預估網站數量（選填，自由文字）",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待處理"),
                            ("contacted", "已聯繫"),
                            ("closed", "已結案"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
