# Generated by Django 5.2.14 on 2026-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_partner_inquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "待處理"),
                    ("contacted", "已聯繫"),
                    ("closed", "已結案"),
                    ("spam", "疑似垃圾訊息"),
                ],
                db_index=True,
                default="new",
                max_length=16,
            ),
        ),
    ]
