# Generated by Django 5.2.14 on 2026-05-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans_and_wallets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ntd', models.PositiveIntegerField()),
                ('coin_amount', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=64)),
                ('buyer_email', models.EmailField(max_length=255)),
                ('invoice_type', models.CharField(choices=[('personal', '個人發票'), ('company', '公司發票')], default='personal', max_length=16)),
                ('company_name', models.CharField(blank=True, max_length=128)),
                ('tax_id', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', '處理中'), ('paid', '已付款'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.pricingplan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.cointransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_pur_user_id_ca6110_idx'), models.Index(fields=['status', '-created_at'], name='billing_pur_status_9992c0_idx')],
            },
        ),
    ]
