# Generated by Django 5.2.14 on 2026-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier_type',
            field=models.CharField(blank=True, choices=[('cloud', '雲端發票（寄 email）'), ('mobile_barcode', '手機條碼'), ('citizen_digital', '自然人憑證')], default='cloud', max_length=24),
        ),
    ]
