# Generated by Django 5.2.14 on 2026-06-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_purchaseorder_carrier_id_purchaseorder_carrier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='balance_after',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='coinwallet',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coinwallet',
            name='total_purchased_ntd',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coinwallet',
            name='total_scans_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
