# Generated by Django 5.2.14 on 2026-09-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_cointransaction_amount_and_more'),
        ('rebuild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='site_rebuild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='rebuild.siterebuild'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='kind',
            field=models.CharField(choices=[('monthly_bonus', '每月贈點'), ('purchase', '購買'), ('scan_hold', '掃描預扣'), ('scan_refund', '掃描退款'), ('admin_adjust', '管理員調整'), ('rebuild_hold', '網頁複刻預扣'), ('rebuild_refund', '網頁複刻退款')], db_index=True, max_length=32),
        ),
    ]
