# Generated by Django 5.2.14 on 2026-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_cointransaction_site_rebuild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='kind',
            field=models.CharField(choices=[('monthly_bonus', '每月贈點'), ('purchase', '購買'), ('scan_hold', '掃描預扣'), ('scan_refund', '掃描退款'), ('admin_adjust', '管理員調整'), ('rebuild_hold', '網頁複刻預扣'), ('rebuild_refund', '網頁複刻退款'), ('fixgen_grant', '修正產出額度贈與'), ('fixgen_charge', '修正產出扣款'), ('fixgen_refund', '修正產出退款')], db_index=True, max_length=32),
        ),
    ]
