# Generated by Django 5.2.14 on 2026-09-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_cointransaction_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('monthly_price_ntd', models.PositiveIntegerField()),
                ('monthly_coins', models.PositiveIntegerField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('badge', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price_ntd'],
            },
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='kind',
            field=models.CharField(choices=[('monthly_bonus', '每月贈點'), ('purchase', '購買'), ('scan_hold', '掃描預扣'), ('scan_refund', '掃描退款'), ('admin_adjust', '管理員調整'), ('rebuild_hold', '網頁複刻預扣'), ('rebuild_refund', '網頁複刻退款'), ('fixgen_grant', '修正產出額度贈與'), ('fixgen_charge', '修正產出扣款'), ('fixgen_refund', '修正產出退款'), ('subscription_grant', '訂閱月贈點')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '生效中'), ('cancelled', '已取消'), ('expired', '已到期')], db_index=True, default='active', max_length=16)),
                ('periods_remaining', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(help_text='下次贈點時間')),
                ('last_grant_period', models.CharField(blank=True, help_text='最近一次已贈點期別，如 "2026-09"（同月冪等用）', max_length=7)),
                ('source', models.CharField(choices=[('admin_grant', '管理員授予'), ('ecpay_test', '綠界測試付款')], max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
