# Generated by Django 5.2.14 on 2026-10-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_seed_subscription_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin_grant", "管理員授予"),
                    ("ecpay_test", "綠界測試付款"),
                    ("ecpay", "綠界定期定額"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_ntd", models.PositiveIntegerField()),
                ("monthly_coins", models.PositiveIntegerField()),
                ("exec_times", models.PositiveSmallIntegerField()),
                ("buyer_name", models.CharField(max_length=64)),
                ("buyer_email", models.EmailField(max_length=255)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("personal", "個人發票"), ("company", "公司發票")],
                        default="personal",
                        max_length=16,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=128)),
                ("tax_id", models.CharField(blank=True, max_length=16)),
                (
                    "carrier_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cloud", "雲端發票（寄 email）"),
                            ("mobile_barcode", "手機條碼"),
                            ("citizen_digital", "自然人憑證"),
                        ],
                        default="cloud",
                        max_length=24,
                    ),
                ),
                ("carrier_id", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待付款"),
                            ("active", "自動續訂中"),
                            ("cancelled", "已取消續訂"),
                            ("failed", "首期付款失敗"),
                            ("ended", "扣款次數已用完"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("success_times", models.PositiveSmallIntegerField(default=0)),
                ("payment_mode", models.CharField(max_length=16)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("succeeded", models.BooleanField()),
                ("amount", models.PositiveIntegerField()),
                ("rtn_code", models.CharField(max_length=10)),
                ("rtn_msg", models.CharField(blank=True, max_length=200)),
                ("provider_ref", models.CharField(blank=True, max_length=40)),
                ("processed_at", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="billing.subscriptionorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionorder",
            index=models.Index(
                fields=["user", "status"], name="billing_sub_user_id_b58610_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptioncharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("succeeded", True)),
                fields=("order", "sequence"),
                name="uniq_successful_subscription_charge",
            ),
        ),
    ]
