# Generated by Django 5.2.14 on 2026-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="handle",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
