# Generated by Django 5.2.14 on 2026-05-25 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('coin_adjust', '調整點數'), ('review_reply', '回覆評論'), ('review_delete', '刪除評論'), ('user_toggle_staff', '切換管理員身份'), ('other', '其他')], db_index=True, max_length=32)),
                ('target_object_repr', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='admin_api_a_action_110e9e_idx'), models.Index(fields=['admin_actor', '-created_at'], name='admin_api_a_admin_a_29d74b_idx')],
            },
        ),
    ]
