# Generated by Django 5.2.14 on 2026-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('permanent', '常駐公告'), ('temporary', '臨時公告')], default='temporary', max_length=16)),
                ('active_days', models.PositiveSmallIntegerField(default=7, help_text='臨時公告從建立日起顯示的天數（常駐公告忽略此欄位）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
