# Generated by Django 5.2.14 on 2026-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_seed_legal_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('coin_adjust', '調整點數'), ('review_reply', '回覆評論'), ('review_moderate', '審核評論'), ('review_delete', '刪除評論'), ('user_toggle_staff', '切換管理員身份'), ('other', '其他')], db_index=True, max_length=32),
        ),
    ]
