# Generated by Django 5.2.14 on 2026-09-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('coin_adjust', '調整點數'), ('subscription_adjust', '調整訂閱'), ('review_reply', '回覆評論'), ('review_moderate', '審核評論'), ('review_delete', '刪除評論'), ('user_toggle_staff', '切換管理員身份'), ('domain_override', '網域驗證人工審核'), ('scan_control', '掃描任務控制'), ('other', '其他')], db_index=True, max_length=32),
        ),
    ]
