# Generated by Django 5.2.14 on 2026-05-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformreview',
            name='admin_replied_at',
        ),
        migrations.RemoveField(
            model_name='platformreview',
            name='admin_replied_by',
        ),
        migrations.RemoveField(
            model_name='platformreview',
            name='admin_reply',
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(db_index=True, default=False)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_messages', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reviews.platformreview')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['review', 'created_at'], name='reviews_rev_review__172819_idx')],
            },
        ),
    ]
