# Generated by Django 5.2.14 on 2026-05-26 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_platformreview_admin_replied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMessageHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='platformreview',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='platformreview',
            index=models.Index(fields=['-is_featured', '-created_at'], name='reviews_pla_is_feat_27e0a9_idx'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='reviews.platformreview'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpfuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmessagehelpful',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='reviews.reviewmessage'),
        ),
        migrations.AddField(
            model_name='reviewmessagehelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_message_helpfuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='uniq_review_helpful'),
        ),
        migrations.AddConstraint(
            model_name='reviewmessagehelpful',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_msg_helpful'),
        ),
    ]
