# Generated by Django 5.2.14 on 2026-07-21 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_review_data(apps, schema_editor):
    platform_review = apps.get_model('reviews', 'PlatformReview')
    review_message = apps.get_model('reviews', 'ReviewMessage')
    review_response = apps.get_model('reviews', 'ReviewResponse')
    scan_job = apps.get_model('scans', 'ScanJob')
    database = schema_editor.connection.alias

    for review in platform_review.objects.using(database).iterator():
        latest_admin_message = (
            review_message.objects.using(database)
            .filter(review_id=review.pk, is_admin=True)
            .exclude(body='')
            .order_by('-created_at', '-pk')
            .first()
        )
        if latest_admin_message:
            response = review_response.objects.using(database).create(
                review_id=review.pk,
                author_id=latest_admin_message.author_id,
                body=latest_admin_message.body,
            )
            review_response.objects.using(database).filter(pk=response.pk).update(
                created_at=latest_admin_message.created_at,
                updated_at=latest_admin_message.created_at,
            )

        latest_scan = (
            scan_job.objects.using(database)
            .filter(user_id=review.user_id, status='completed')
            .order_by('-completed_at', '-created_at')
            .values('completed_at', 'created_at')
            .first()
        )
        if latest_scan:
            platform_review.objects.using(database).filter(pk=review.pk).update(
                experience_at=latest_scan['completed_at'] or latest_scan['created_at'],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewhelpful_reviewmessagehelpful_and_more'),
        ('scans', '0009_finding_cwe_id_finding_owasp_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾或廣告'), ('privacy', '揭露個資'), ('abuse', '仇恨、騷擾或不當內容'), ('other', '其他')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('resolved', '已處理'), ('dismissed', '不成立')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platformreview',
            name='display_name',
            field=models.CharField(blank=True, help_text='公開顯示名稱；留白時顯示為匿名已驗證使用者。', max_length=32),
        ),
        migrations.AddField(
            model_name='platformreview',
            name='experience_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformreview',
            name='status',
            field=models.CharField(choices=[('published', '公開'), ('hidden', '已隱藏')], db_index=True, default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='platformreview',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='platformreview',
            index=models.Index(fields=['status', '-created_at'], name='reviews_pla_status_d1b8d8_idx'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.platformreview'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_response', to='reviews.platformreview'),
        ),
        migrations.AddField(
            model_name='reviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='reviews.platformreview'),
        ),
        migrations.RunPython(migrate_legacy_review_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reporter'), name='uniq_review_reporter'),
        ),
    ]
